-- Lista blanca de calles/colonias dentro del radio de cobertura
-- Fecha: 2026-08-23
--
-- Contexto: CLAUDE.md Regla de oro #1 exige validar que toda entrega caiga
-- dentro del radio de cobertura, usando GPS (Haversine). Se detectó que una
-- dirección escrita en texto (sin GPS) podía pasar la validación de
-- captura sin que NINGUNA verificación geográfica se ejecutara nunca —
-- Golden Rule #1 no se estaba aplicando para ese camino.
--
-- Esta tabla es la solución elegida con Víctor (opción C de tres): en vez de
-- exigir GPS siempre (bloquea el caso de uso que pidió) o confiar en el
-- texto a ciegas (relaja la regla sin verificación real), se mantiene una
-- lista de calles/colonias ya confirmadas dentro del radio de 1.5km. La IA
-- compara la dirección escrita contra esta lista (inyectada en el prompt,
-- mismo patrón que NEGOCIOS DISPONIBLES) y el backend verifica con match
-- exacto contra esta tabla — igual que resolveTiendaStrictByName ya hace
-- para el nombre de la tienda: la IA sugiere, la BD real decide.
--
-- Alta de zonas nuevas: manual, la hace Víctor directo en el SQL Editor
-- (mismo patrón que altas de tiendas/repartidores, CLAUDE.md Sección 5):
--   insert into public.zonas_cobertura (nombre) values ('Calle Nueva');
-- No hace falta ningún deploy de código para que la zona nueva empiece a
-- usarse — el bot la lee fresca de la tabla en cada turno.

create table if not exists public.zonas_cobertura (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activa boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists zonas_cobertura_activa_idx on public.zonas_cobertura (activa);

insert into public.zonas_cobertura (nombre) values
  ('Calle Pino'),
  ('Colonia San José'),
  ('Calle Morelos'),
  ('Calle Abasolo'),
  ('Calle Independencia'),
  ('Calle Javier Mina'),
  ('Calle Venustiano Carranza'),
  ('Boulevard Juan Pablo II'),
  ('Calle Delicias'),
  ('Calle Galeana'),
  ('Centro (Ixtlahuacán del Río)')
on conflict (nombre) do nothing;
