-- Fase 1 de la migración al esquema definitivo (CLAUDE.md, Sección 4)
-- Fecha: 2026-08-04
--
-- Objetivo de esta fase (100% aditiva):
-- - Crear, EN PARALELO, las tablas del esquema definitivo: tiendas, repartidores_new,
--   clientes_new, productos_tienda, pedidos_new, pedido_tiendas, pedido_items_new.
-- - Rellenarlas (backfill) con los datos maestros de prueba que ya existen hoy
--   (negocios, repartidores, clientes) — SIN pedidos, porque no hay pedidos reales
--   que conservar (confirmado por Víctor).
-- - NO se renombra, NO se altera y NO se borra ninguna tabla existente aquí.
--   El código en producción (que sigue leyendo/escribiendo negocios/repartidores/
--   clientes/pedidos/pedidos_v2/pedido_items) sigue funcionando exactamente igual
--   mientras esta migración esté aplicada mas no "activada" por el código nuevo.
-- - El corte real (renombrar estas tablas a sus nombres finales y retirar las legacy)
--   ocurre en la Fase 3, junto con el despliegue del código de la Fase 2.
--
-- Nota sobre nombres de columna: `productos_tienda` y `pedido_items` usan ambas
-- `nombre_producto` (se corrigió una errata del CLAUDE.md original, que tenía
-- `producto_nombre` en pedido_items — ya unificado también en el documento).

-- =========================
-- Enums del esquema definitivo
-- =========================

-- Estado del pedido: exactamente los 11 valores de la Sección 7 del CLAUDE.md,
-- en el mismo orden documentado. Reemplaza (para el pedido "pedidos" nuevo) al
-- enum pedido_estado_flujo de Bloque 7, que tenía 12 valores y no correspondía
-- 1:1 con el vocabulario del documento.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'pedido_estado') then
    create type public.pedido_estado as enum (
      'seleccion_productos',
      'confirmacion_cliente',
      'pendiente_tiendas',
      'ajuste_producto',
      'confirmado_tiendas',
      'dispatch_repartidor_pendiente',
      'repartidor_asignado',
      'recogiendo',
      'en_camino_cliente',
      'entregado',
      'cancelado'
    );
  end if;
end $$;

-- Estado de cada tienda dentro de un pedido multi-tienda (Sección 4: pedido_tiendas).
do $$
begin
  if not exists (select 1 from pg_type where typname = 'pedido_tienda_estado') then
    create type public.pedido_tienda_estado as enum (
      'pendiente',
      'confirmado',
      'ajuste_producto',
      'cancelado'
    );
  end if;
end $$;

-- =========================
-- TIENDAS (reemplazo definitivo de "negocios")
-- =========================
-- Se crea como tabla nueva (no ALTER/RENAME de "negocios") para no romper el
-- código actual, que sigue apuntando a "negocios" hasta la Fase 3.
-- Se preservan los mismos `id` que en "negocios" para que cualquier FK futura
-- (p. ej. productos_tienda.tienda_id) siga siendo válida sin necesidad de mapeo.
--
-- Decisión de criterio (no viene explícita en la Sección 4, se las señalo a
-- Víctor para que las revise): se conserva `categoria`, porque el código actual
-- (getLLMResponse en mandaloFlow.ts) la usa activamente para describirle la
-- tienda al modelo. Se descartan los campos de facturación/premium de Bloque 7
-- (slug, descripcion, zona_servicio, acepta_contra_entrega, liquidacion_*,
-- prioridad_posicionamiento, premium_activo, metadata_json) por no estar en el
-- spec y no tener ningún uso real en el código hoy.
create table if not exists public.tiendas (
  id bigint generated by default as identity primary key,
  nombre text,
  categoria text,
  telefono text,
  direccion text,
  activa boolean not null default true,
  hora_apertura text,
  hora_cierre text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

drop trigger if exists trg_tiendas_updated_at on public.tiendas;
create trigger trg_tiendas_updated_at
before update on public.tiendas
for each row execute function public.set_updated_at();

create index if not exists tiendas_activa_idx on public.tiendas (activa);
create index if not exists tiendas_telefono_idx on public.tiendas (telefono);

insert into public.tiendas (id, nombre, categoria, telefono, direccion, activa, hora_apertura, hora_cierre, created_at)
select
  n.id,
  n.nombre,
  n.categoria,
  n.whatsapp,
  n.direccion_texto,
  coalesce(n.activo, true),
  n.horario_apertura,
  n.horario_cierre,
  n.created_at
from public.negocios n
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.tiendas', 'id'),
  coalesce((select max(id) from public.tiendas), 1)
);

-- =========================
-- REPARTIDORES_NEW (reemplazo definitivo de "repartidores")
-- =========================
-- Mismo criterio que tiendas: tabla nueva y separada, mismos `id` que el original.
-- Se agrega `disponible`, que hoy no existe en ningún lado y es indispensable para
-- la regla de "notificar a todos los repartidores activos, el primero que confirme
-- se lo queda" (Sección 8). Se conserva `vehiculo` (dato real, bajo riesgo de
-- mantener aunque no esté listado en el spec).
create table if not exists public.repartidores_new (
  id bigint generated by default as identity primary key,
  nombre text,
  telefono text,
  vehiculo text,
  disponible boolean not null default true,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

drop trigger if exists trg_repartidores_new_updated_at on public.repartidores_new;
create trigger trg_repartidores_new_updated_at
before update on public.repartidores_new
for each row execute function public.set_updated_at();

create index if not exists repartidores_new_activo_idx on public.repartidores_new (activo, disponible);
create index if not exists repartidores_new_telefono_idx on public.repartidores_new (telefono);

insert into public.repartidores_new (id, nombre, telefono, vehiculo, disponible, activo, created_at)
select
  r.id,
  r.nombre,
  r.whatsapp,
  r.vehiculo,
  coalesce(r.activo, true), -- disponible arranca igual a activo; se opera aparte desde ahora
  coalesce(r.activo, true),
  r.created_at
from public.repartidores r
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.repartidores_new', 'id'),
  coalesce((select max(id) from public.repartidores_new), 1)
);

-- =========================
-- CLIENTES_NEW (reemplazo definitivo de "clientes")
-- =========================
-- PK cambia de `id` a `telefono`, tal como pide la Sección 4 — por eso no puede
-- hacerse con un ALTER simple, se requiere tabla nueva.
-- Se agregan `latitud`/`longitud`: la columna que faltaba y que ya identificamos
-- como necesaria para guardar el PIN de GPS real (Regla de oro #1).
create table if not exists public.clientes_new (
  telefono text primary key,
  nombre text,
  direccion_entrega text,
  latitud double precision,
  longitud double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

drop trigger if exists trg_clientes_new_updated_at on public.clientes_new;
create trigger trg_clientes_new_updated_at
before update on public.clientes_new
for each row execute function public.set_updated_at();

insert into public.clientes_new (telefono, nombre, direccion_entrega, created_at)
select
  c.telefono,
  c.nombre_preferido,
  c.ultima_direccion_texto,
  c.created_at
from public.clientes c
where c.telefono is not null
on conflict (telefono) do nothing;

-- =========================
-- PRODUCTOS_TIENDA (reemplazo definitivo de "negocio_productos")
-- =========================
create table if not exists public.productos_tienda (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null references public.tiendas(id) on delete cascade,
  nombre_producto text not null,
  precio numeric,
  disponible boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists productos_tienda_tienda_idx on public.productos_tienda (tienda_id, disponible);

do $$
begin
  if not exists (select 1 from public.productos_tienda) then
    insert into public.productos_tienda (tienda_id, nombre_producto, precio, disponible, created_at)
    select
      np.negocio_id,
      np.nombre_visible,
      np.precio_referencia,
      coalesce(np.disponible, true),
      np.created_at
    from public.negocio_productos np
    where exists (select 1 from public.tiendas t where t.id = np.negocio_id);
  end if;
end $$;

-- =========================
-- PEDIDOS_NEW (reemplazo definitivo de "pedidos" + "pedidos_v2")
-- =========================
-- Sin backfill: no hay pedidos reales que conservar (confirmado). Arranca vacía.
create table if not exists public.pedidos_new (
  id bigint generated by default as identity primary key,
  cliente_telefono text not null references public.clientes_new(telefono) on delete restrict,
  repartidor_id bigint references public.repartidores_new(id) on delete set null,
  estado public.pedido_estado not null default 'seleccion_productos',
  direccion_entrega text,
  latitud double precision,
  longitud double precision,
  servicio_mandalo numeric not null default 20,
  servicio_repartidor numeric,
  total_cliente numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

drop trigger if exists trg_pedidos_new_updated_at on public.pedidos_new;
create trigger trg_pedidos_new_updated_at
before update on public.pedidos_new
for each row execute function public.set_updated_at();

create index if not exists pedidos_new_cliente_idx on public.pedidos_new (cliente_telefono, created_at desc);
create index if not exists pedidos_new_repartidor_idx on public.pedidos_new (repartidor_id);
create index if not exists pedidos_new_estado_idx on public.pedidos_new (estado, created_at desc);

-- =========================
-- PEDIDO_TIENDAS (nueva — hoy no existe en ninguna forma)
-- =========================
-- Habilita pedidos multi-tienda a nivel de esquema. El flujo del bot, por ahora,
-- seguirá usando una sola tienda por pedido (según lo acordado) — esta tabla
-- queda lista para cuando se construya el soporte real más adelante.
create table if not exists public.pedido_tiendas (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos_new(id) on delete cascade,
  tienda_id bigint not null references public.tiendas(id) on delete restrict,
  subtotal_tienda numeric,
  estado_tienda public.pedido_tienda_estado not null default 'pendiente',
  created_at timestamptz not null default now()
);

create index if not exists pedido_tiendas_pedido_idx on public.pedido_tiendas (pedido_id);
create index if not exists pedido_tiendas_tienda_idx on public.pedido_tiendas (tienda_id);

-- =========================
-- PEDIDO_ITEMS_NEW (reemplazo definitivo de "pedido_items")
-- =========================
-- Ahora cuelga de pedido_tiendas (no del pedido directo), y usa una sola columna
-- de texto libre para el producto — sin marca/presentación/notas por separado,
-- tal como se acordó (apegado al spec exacto).
create table if not exists public.pedido_items_new (
  id bigint generated by default as identity primary key,
  pedido_tienda_id bigint not null references public.pedido_tiendas(id) on delete cascade,
  nombre_producto text not null,
  cantidad numeric,
  disponible boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists pedido_items_new_pedido_tienda_idx on public.pedido_items_new (pedido_tienda_id);

-- =========================
-- Retención en cascada (prepara la Fase 4)
-- =========================
-- Gracias al "on delete cascade" de pedido_tiendas -> pedidos_new y de
-- pedido_items_new -> pedido_tiendas, borrar una fila de pedidos_new (cuando
-- llegue a 'entregado'/'cancelado', en la Fase 4) limpia todo lo demás solo,
-- sin necesidad de lógica adicional de borrado en cascada manual.

-- =========================
-- Seguridad (RLS) — mismo criterio que Bloque 7: bloqueado por defecto,
-- solo accesible vía service_role. Sin policies (no hay panel admin todavía).
-- =========================
alter table public.tiendas enable row level security;
alter table public.repartidores_new enable row level security;
alter table public.clientes_new enable row level security;
alter table public.productos_tienda enable row level security;
alter table public.pedidos_new enable row level security;
alter table public.pedido_tiendas enable row level security;
alter table public.pedido_items_new enable row level security;
