-- Mándalo - esquema mínimo basado en el Blueprint (Make)
-- Tablas: negocios, repartidores, pedidos

-- NEGOCIOS
create table if not exists public.negocios (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  whatsapp text,
  nombre text,
  categoria text,
  horario_apertura text,
  horario_cierre text
);

create index if not exists negocios_whatsapp_idx on public.negocios (whatsapp);

-- REPARTIDORES
create table if not exists public.repartidores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text,
  whatsapp text,
  activo boolean not null default true,
  vehiculo text
);

create index if not exists repartidores_activo_idx on public.repartidores (activo);
create index if not exists repartidores_whatsapp_idx on public.repartidores (whatsapp);

-- PEDIDOS / HISTORIAL
-- Nota: para replicar el flujo del Blueprint, esta tabla se usa como "registro" de:
-- - mensajes del cliente (estado='cliente')
-- - mensajes del bot (estado='bot')
-- - cotizaciones pendientes (estado='pendiente')
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  telefono_cliente text,
  detalle_pedido text,
  total numeric,
  estado text
);

create index if not exists pedidos_telefono_cliente_created_at_idx
  on public.pedidos (telefono_cliente, created_at desc);

